apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{.Values.storageclass.name}}
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer 