version: '3.7'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: root
       #MYSQL_USER: root
       MYSQL_PASSWORD: root
     ports:
     - 33066:3306
   app:
     depends_on:
       - db
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "8080:8080"
     restart: always
     environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=db'
volumes:
    db_data:
