apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        name: app
        ports:
        - containerPort: 9090
        env:
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_HOST
          value: {{.Values.mysql.name}}-h
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
                

---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-svc
  labels:
    app: {{.Values.app.name}}-svc
spec:
  ports:
  - port: 9090
  selector:
    app: {{.Values.app.name}}
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{.Values.mysql.name}}
  name: {{.Values.mysql.name}}
spec:
  replicas: {{.Values.mysql.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.mysql.name}}
  serviceName: {{.Values.mysql.name}}-h
  template:
    metadata:
      labels:
        app: {{.Values.mysql.name}}
    spec:
      containers:
      - image: {{.Values.mysql.image.repository}}:{{.Values.mysql.image.tag}}
        name: {{.Values.mysql.name}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name:  MYSQL_DATABASE
          value: "root"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: {{.Values.mysql.volumeclaim.name}}
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: {{.Values.mysql.volumeclaim.name}}
    spec:
      accessModes: 
      - ReadWriteOnce
      storageClassName: gp2
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mysql.name}}-h
spec:
  clusterIP: None
  selector:
    app: {{.Values.mysql.name}}
  ports:
  - port: 3306
    targetPort: 3306
---
