app:
  name: app
  replicaCount: 2
  minreplicas: 1
  maxreplicas: 3
  average_utilization: 70
  image:
    repository: melmesary/app
    tag: v1.1

mysql:
  replicaCount: 2
  minreplicas: 1
  maxreplicas: 3
  average_utilization: 70
  name: mysql
  image:
    repository: mysql
    tag: latest
  volumeclaimtemplates:
    name: data-vol
    spec:
      accessmodes: ReadWriteOnce
      resources:
        request:
          storage: 1Gi
  username: root
  password: root

storageclass:
  name: "ebs-storage"